apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: ftps20
    port: 20
    targetPort: 20
    protocol: TCP
  - name: ftps21
    port: 21
    targetPort: 21
  - name: ftps21000
    port: 21000
    targetPort: 21000
  - name: ftps21001
    port: 21001
    targetPort: 21001
  - name: ftps21002
    port: 21002
    targetPort: 21002
  - name: ftps21003
    port: 21003
    targetPort: 21003
  - name: ftps21004
    port: 21004
    targetPort: 21004
  - name: ftps21005
    port: 21005
    targetPort: 21005
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_image
        # set imagePullPolicy to never so we can use local images
        imagePullPolicy: Never
        name: ftps
        ports:

        - containerPort: 21
        - containerPort: 20
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
        - containerPort: 21004
        - containerPort: 21005
