apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  ports:
    - port: 8086
  selector:
    app: influxdb
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # must be carefull bcs its a pain to change the storage capacity after its been mounted (protected)
      # to delete volume  :
      # kubectl patch pvc PVC_NAME -p '{"metadata":{"finalizers": []}}' --type=merge
      # kubectl delete pvc PVC_NAME
      # mb repatch with the first step if its still in terminating process (kubectl get pvc)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb_image
        # set imagePullPolicy to never so we can use local images
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /probe.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
