apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  ports:
    - name: phpmyadmin
      port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin_image
        # set imagePullPolicy to never so we can use local images
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /probe.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        name: phpmyadmin
        ports:
        - containerPort: 5000
          name: phpmyadmin
