apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: telegraf_image
          imagePullPolicy: Never
          name: telegraf
          ports:
          - containerPort: 8125
          volumeMounts:
          - name: telegraf-endpoint
            mountPath: "/var/run/docker.sock"
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  ports:
    - name: telegraf
      port: 8125
      protocol: UDP
      targetPort: 8125
  selector:
    app: telegraf
  type: ClusterIP
