apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
  labels:
    app: wordpress
spec:
  ports:
    - name: wordpress
      port: 5050
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.49.2
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress_image
        # set imagePullPolicy to never so we can use local images
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - /probe.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        name: wordpress
        ports:
        - containerPort: 5050
          name: wordpress
